/Library/Frameworks/Python.framework/Versions/3.12/bin/python3: can't find '__main__' module in '/Users/mac/Documents/pythonProjects/Notion-and-Google-Calendar-2-Way-Sync-main'
/Library/Frameworks/Python.framework/Versions/3.12/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/mac/Documents/pythonProjects/Notion-and-Google-Calendar-2-Way-Sync-main/flask_app.py': [Errno 2] No such file or directory
/Library/Frameworks/Python.framework/Versions/3.12/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/mac/Documents/pythonProjects/Notion-and-Google-Calendar-2-Way-Sync-main/flask_app.py': [Errno 2] No such file or directory
/Library/Frameworks/Python.framework/Versions/3.12/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/mac/Documents/pythonProjects/Notion-and-Google-Calendar-2-Way-Sync-main/flask_app.py': [Errno 2] No such file or directory


 * Serving Flask app 'flask_app'
 * Debug mode: off
[1m[36m.[0m[1m[36m.[0m[1m[36m.[0m[1m[36m.[0mException in thread Thread-1 (dynamic_counter_indicator):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/mac/Desktop/GCal-Notion-Sync/flask_app.py", line 201, in dynamic_counter_indicator
    terminal_width = os.get_terminal_size().columns  # Get the width of the terminal
                     ^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 25] Inappropriate ioctl for device
